[package]
authors = ["The Rust Project Developers"]
name = "rustc_highlight"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustc_highlight"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
log = "0.4"
syntax = { path = "../libsyntax" }
syntax_pos = { path = "../libsyntax_pos" }
